# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Theme Index"
license = "MIT"
licenselink = "./LICENSE.md"
description = "Hugo personal theme"
homepage = "https://github.com/Indexyz/hugo-theme-index"
repo = "https://github.com/Indexyz/hugo-theme-index"
tags = ["blog"]
features = ["blog"]
min_version = 0.38

[author]
  name = "Indexyz"
  homepage = "https://blog.indexyz.me/"
